#ifndef NEURALNETWORK_H
#define NEURALNETWORK_H

#define INPUT_LAYER_SIZE 784
#define HIDDEN_LAYER1_SIZE 1000
#define HIDDEN_LAYER2_SIZE 1000
#define OUTPUT_LAYER_SIZE 10




#endif  // NEURALNETWORK_H